project:
  type: website
  output-dir: docs

website:
  title: "Mary Wu"
  search: true
  navbar:
    background: light
    left:
      - file: index.qmd
        text: "Home"
      - sidebar:mini_projects

      
  sidebar:
    - id: mini_projects
      title: "Mini Project 1"
      contents: 
        - WI_Gerrymandering.qmd
        - US_States_and_Minimum_Wage.qmd
      
  page-footer:
    left: |
      &copy; Mary Wu, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source




  
